query Stations(
  $companyIds: [String]
  $north: Float
  $south: Float
  $east: Float
  $west: Float
) {
  stations(
    companyIds: $companyIds
    north: $north
    south: $south
    east: $east
    west: $west
  ) {
    id
    lat
    lon
    company {
      id
      name
      logo_img
    }
  }
}

query Station($stationId: ID!) {
  station(id: $stationId) {
    id
    pricesHistory {
      id
      currency
      price
      updatedAt
      date
      type {
        id
        name
        description
        superType {
          cat
          name
          id
        }
      }
    }
    prices {
      id
      currency
      price
      date
      type {
        id
        name
        description
        superType {
          cat
          name
          id
        }
      }
    }
  }
}

query CurrentPrices($stationId: ID!) {
  station(id: $stationId) {
    id
    prices {
      id
      currency
      price
      date
      updatedAt
      type {
        id
        name
        description
        superType {
          cat
          name
          id
        }
      }
    }
  }
}

query StationAvailablePetrols($stationId: ID!) {
  station(id: $stationId) {
    id
    company {
      id
      availablePetrols {
        id
        name
        description
        superType {
          id
          name
          cat
        }
      }
    }
  }
}
