import Box from "@mui/material/Box";
import type { NextPage } from "next";
import Head from "next/head";
import { useRecoilValue } from "recoil";
import InfoPanel from "../components/infopanel/infopanel";
import MainLayout from "../components/layout/main-layout";
import DynamicMap from "../components/map/mapdynamic";
import selectedStation from "../src/atoms/selected-station";

// const drawerWidth = 500;

const Home: NextPage = () => {
  // const selected = useRecoilValue(selectedStation);

  // const w = selected ? drawerWidth : 0;

  return (
    <MainLayout>
      <Head>
        <title>Kde Natankuju</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        sx={{
          width: "100%",
          // width: `calc(100% - ${w}px)`,
          // mr: `${w}px`,
          height: "100vh",
        }}
      >
        <DynamicMap />
        <InfoPanel />
      </Box>
    </MainLayout>
  );
};

export default Home;
