import Box from "@mui/material/Box";
import type { NextPage } from "next";
import Head from "next/head";
import InfoPanel from "../components/infopanel/infopanel";
import DynamicMap from "../components/map/mapdynamic";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Kde Natankuju</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ width: "100vw", height: "100vh" }}>
        <DynamicMap />
        <InfoPanel />
      </Box>
    </div>
  );
};

export default Home;
